name: Test latest version

on:
  push:
    branches: [ latest ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install -r requirements.txt
    - name: Setup
      run: |
        cd tools && echo "all" | python setup.py
    - name: Test
      run: |
        cd tests && chmod +x ./run_tests.sh && ./run_tests.sh